AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Bucket"

Parameters:
  ResourceNameSuffix:
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "s3-bucket-basic-${ResourceNameSuffix}"
      DeletionPolicy: Delete